# Generated by Django 4.1.3 on 2022-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Usario')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('constraseña', models.CharField(max_length=50, verbose_name='Constraseña')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
            ],
        ),
    ]
